version: "3"

volumes:
  nginx-vol:

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${SERVER_HOST}
    env_file: .env
    expose:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${NGINX_HOST}
    env_file: .env
    expose:
      - "${NGINX_PORT}:80"
